name: Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - 'android-app/**'
      - 'library/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - 'android-app/**'
      - 'library/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/android-app/.gradle/caches
          ~/android-app/.gradle/wrapper
          ~/library/.gradle/caches
          ~/library/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew (library)
      run: chmod +x gradlew
      working-directory: ./library

    - name: Grant execute permission for gradlew (android-app)
      run: chmod +x gradlew
      working-directory: ./android-app

    - name: APDU library Build
      run: ./gradlew assemble
      working-directory: ./library

    - name: APDU library Test
      run: ./gradlew test jacocoTestReport
      working-directory: ./library

    - name: Publish Test Report
      uses: Madrapps/jacoco-report@v1.7.1
      with:
        paths: ${{ github.workspace }}/library/apdu/build/reports/jacoco/test/jacocoTestReport.xml,${{ github.workspace }}/library/apdu-command/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Library Coverage Report
        update-comment: true

    - name: Android Build
      run: ./gradlew assemble
      working-directory: ./android-app

    - name: Android Test
      run: ./gradlew test
      working-directory: ./android-app
